all:
  hosts:
    node1:
      ansible_host: HOSTNAME
      ansible_ssh_host: IP_ADDRESS
    node2:
      ansible_host: HOSTNAME
      ansible_ssh_host: IP_ADDRESS
  vars:
    user_name: USERNAME
    ssh_port: SSHPORT
